# Generated by Django 3.2.9 on 2021-11-02 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, default='default-image.jpg', upload_to='movies_images')),
                ('genre', models.CharField(blank=True, max_length=200)),
                ('imdb_rating', models.CharField(max_length=10)),
                ('imdb_id', models.CharField(max_length=20, unique=True)),
                ('released_date', models.DateField()),
                ('endYear', models.DateField(blank=True)),
                ('language', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('actors', models.CharField(max_length=400)),
                ('run_time', models.TimeField()),
                ('totalSeason', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movies', models.ManyToManyField(to='api.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
