# Generated by Django 3.2.9 on 2021-11-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_movie_run_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='totalSeason',
            field=models.CharField(max_length=10),
        ),
    ]
