# Generated by Django 3.2.9 on 2021-11-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_movie_run_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='endYear',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_rating',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='released_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='run_time',
            field=models.PositiveIntegerField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='totalSeason',
            field=models.PositiveIntegerField(max_length=10, null=True),
        ),
    ]
