# Generated by Django 3.2.9 on 2021-11-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211102_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='run_time',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='totalSeason',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
